- id: '1568213287323'
  alias: Weg in de ochtend.
  trigger:
  - entity_id: device_tracker.telefoon_erik
    from: home
    platform: state
    to: not_home
  - entity_id: device_tracker.oneplus5t
    from: home
    platform: state
    to: not_home
  condition:
  - condition: state
    entity_id: person.erik_van_der_bas
    state: not_home
  - condition: state
    entity_id: person.marileen
    state: not_home
  action:
  - data:
      entity_id: all
      language: nl
      message: Erik, ga niet weg. Ik mis je.
    service: tts.google_translate_say
- id: '1568384852404'
  alias: Zet de Stereo aan als de Chromecast begint te spelen.
  trigger:
  - entity_id: media_player.huiskamer
    from: paused
    platform: state
    to: playing
  condition: []
  action:
  - data:
      entity_id: switch.switch_music_downstairs
    service: switch.turn_on
- id: '1569138214205'
  alias: Zet stereo uit na 15 minuten pauze
  trigger:
  - entity_id: media_player.huiskamer
    for: 00:15:00
    from: playing
    platform: state
    to: paused
  condition: []
  action:
  - data:
      entity_id: switch.switch_music_downstairs
    service: switch.turn_off
- id: '1570216531721'
  alias: Stroom van computer onder 4 Watt
  trigger:
  - below: '4'
    entity_id: sensor.sonoff_switch_desk_energy_power
    for: 00:10:00
    platform: numeric_state
  condition: []
  action:
  - data: {}
    entity_id: switch.sonoff_switch_desk
    service: switch.turn_off
  - entity_id: switch.sonoff_switch_music_upstairs
    service: switch.turn_off
- id: '1570300078319'
  alias: Slaapkamer lamp uit om 9 uur
  trigger:
  - at: 09:00
    platform: time
  condition:
  - condition: state
    entity_id: light.philips_bloom
    state: 'on'
  action:
  - data:
      entity_id: light.philips_bloom
    service: light.turn_off
- id: '1571837838932'
  alias: Blob aan als de deur open gaat en niemand thuis is
  description: Alleen na zonsondergang
  trigger:
  - entity_id: binary_sensor.deur_woonkamer
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.deur_hal
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: sunset
    condition: sun
  - condition: template
    value_template: "{{ is_state('person.erik_van_der_bas', 'away') or\n         as_timestamp(now())\
      \ - as_timestamp(states.person.erik_van_der_bas.last_changed)\n         < 5*60\
      \ }}"
  - condition: template
    value_template: "{{ is_state('person.marileen', 'away') or\n         as_timestamp(now())\
      \ - as_timestamp(states.person.marileen.last_changed)\n         < 5*60 }}"
  action:
  - entity_id: light.blob
    service: light.turn_on
  - entity_id: light.eettafel
    service: light.turn_on
- id: '1571839650328'
  alias: Licht aan in hal
  description: ''
  trigger:
  - entity_id: binary_sensor.deur_woonkamer
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.deur_hal
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.sonoff_switch_hall
    state: 'off'
  action:
  - data: {}
    entity_id: switch.sonoff_switch_hall
    service: switch.turn_on
  - delay: 00:02:00
  - data: {}
    entity_id: switch.sonoff_switch_hall
    service: switch.turn_off
- id: '1572110838623'
  alias: Licht werkkamer dimmen na zonsondergang
  description: ''
  trigger:
  - device_id: 2700d554b05e46d0ad27df6357d67e8d
    domain: light
    entity_id: light.lamp_werkkamer
    platform: device
    type: turned_on
  condition:
  - after: sunset
    condition: sun
  action:
  - data:
      brightness: 100
      entity_id: light.werkkamer
      transition: 5
    service: light.turn_on
- id: '1573073003121'
  alias: badkamer dimmen
  description: Badkamer licht dimmen na 9 uur
  trigger:
  - entity_id: light.badkamerlamp
    platform: state
    to: 'on'
  condition:
  - after: '21:00:00'
    before: 08:00:00
    condition: time
  action:
  - data:
      brightness: 120
      entity_id: light.badkamerlamp
    service: light.turn_on
- id: '1574879017101'
  alias: Blob aan bij beweging in de nacht
  description: ''
  trigger:
  - entity_id: binary_sensor.motion_livingroom
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: state
    entity_id: light.eettafel
    state: 'off'
  - condition: state
    entity_id: light.blob
    state: 'off'
  action:
  - data:
      brightness: 44
      color_temp: 432
      entity_id: light.blob
    service: light.turn_on
  - data:
      entity_id: switch.sonoff_switch_backup
    service: switch.turn_on
  - delay: 00:04:00
  - data:
      entity_id: light.blob
    service: light.turn_off
  - data:
      entity_id: switch.sonoff_switch_backup
    service: switch.turn_off
- id: tasmota_auto_discovery
  alias: Sync Tasmota states on start-up - autodiscovery
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: tasmotas/cmnd/state
      payload: ''
- id: '1585034107862'
  alias: muziek boven uit om 22:00
  description: ''
  trigger:
  - at: '22:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: switch.sonoff_switch_music_upstairs
    service: switch.turn_off
- id: '1589008788991'
  alias: Notify everyone when washingmachine is ready
  description: ''
  trigger:
  - entity_id: sensor.washer_samsung_washer_machine_state
    from: run
    platform: state
    to: stop
  condition: []
  action:
    - service: notify.notify
      data_template:
        message: De wasmachine is klaar sinds {{ now().strftime('%H:%M') }}
        title: Wasmachine klaar.
