- id: '1568213287323'
  alias: Weg in de ochtend.
  trigger:
  - entity_id: device_tracker.telefoon_erik
    from: home
    platform: state
    to: not_home
  - entity_id: device_tracker.oneplus5t
    from: home
    platform: state
    to: not_home
  condition:
  - condition: state
    entity_id: person.erik_van_der_bas
    state: not_home
  - condition: state
    entity_id: person.marileen
    state: not_home
  action:
  - data:
      entity_id: all
      language: nl
      message: Erik, ga niet weg. Ik mis je.
    service: tts.google_translate_say
- id: '1568384852404'
  alias: Zet de Stereo aan als de Chromecast begint te spelen.
  trigger:
  - entity_id: media_player.huiskamer
    from: paused
    platform: state
    to: playing
  condition: []
  action:
    data:
      entity_id: switch.sonoff_switch_music_downstairs
    service: switch.turn_on
- id: '1569138214205'
  alias: Zet stereo uit na 15 minuten pauze
  trigger:
  - entity_id: media_player.huiskamer
    for: 00:15:00
    from: playing
    platform: state
    to: paused
  condition: []
  action:
  - data:
      entity_id: switch.sonoff_switch_music_downstairs
    service: switch.turn_off
- alias: Power state on HA start-up
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: sonoffs/cmnd/state
      payload: ''
  id: fcb40382a204462bbbf5704f118b4728
- alias: Enable MQTT discovery for all devices
  trigger:
    platform: homeassistant
    event: start
  action:
  - data:
      entity_id: switch.sonoff_2
    service: homeassistant.turn_off
  id: c696924d994e4c76bcaddf166469b739
- id: '1570216531721'
  alias: Stroom van computer onder 4 Watt
  trigger:
  - below: '4'
    entity_id: sensor.sonoff_energy_power_4
    for: 00:10:00
    platform: numeric_state
  condition: []
  action:
    data:
      entity_id: switch.sonoff_switch_pc
    service: switch.turn_off
- id: '1570300078319'
  alias: Slaapkamer lamp uit om 9 uur
  trigger:
  - at: 09:00
    platform: time
  condition:
  - condition: state
    entity_id: light.philips_bloom
    state: 'on'
  action:
    data:
      entity_id: light.philips_bloom
    service: light.turn_off
- id: '1571837838932'
  alias: Blob aan als de deur open gaat en niemand thuis is
  description: ''
  trigger:
  - device_id: 7ee85ef0953c4daf94eea8578e5496dd
    domain: binary_sensor
    entity_id: binary_sensor.window_door_sensor_2
    platform: device
    type: opened
  - device_id: d8fa9af57d9c48bc871823c5d852aab3
    domain: binary_sensor
    entity_id: binary_sensor.window_door_sensor
    platform: device
    type: opened
  condition:
  - after: sunset
    condition: sun
  - condition: template
    value_template: "{{ is_state('person.erik_van_der_bas', 'away') or\n         as_timestamp(now())\
      \ - as_timestamp(states.person.erik_van_der_bas.last_changed)\n         < 5*60\
      \ }}"
  - condition: template
    value_template: "{{ is_state('person.marileen', 'away') or\n         as_timestamp(now())\
      \ - as_timestamp(states.person.marileen.last_changed)\n         < 5*60 }}"
  action:
  - device_id: 8bc40eccc1c744219d82319504cea95b
    domain: light
    entity_id: light.blob
    type: turn_on
  - device_id: 409569def8bd48d8918c5f6ba62a7b06
    domain: light
    entity_id: light.eettafel
    type: turn_on
- id: '1571839650328'
  alias: Licht aan in hal
  description: ''
  trigger:
  - device_id: 7ee85ef0953c4daf94eea8578e5496dd
    domain: binary_sensor
    entity_id: binary_sensor.window_door_sensor_2
    platform: device
    type: opened
  - device_id: d8fa9af57d9c48bc871823c5d852aab3
    domain: binary_sensor
    entity_id: binary_sensor.window_door_sensor
    platform: device
    type: opened
  condition:
  - condition: device
    device_id: 70751c54d879498e80584fa9c7f5a663
    domain: switch
    entity_id: switch.sonoff_switch_hall
    type: is_off
  action:
  - alias: ''
    data:
      entity_id: switch.sonoff_switch_hall
    service: homeassistant.turn_on
  - delay: 00:02:00
  - alias: ''
    data:
      entity_id: switch.sonoff_switch_hall
    service: homeassistant.turn_off
- id: '1572110838623'
  alias: Licht werkkamer dimmen na zonsondergang
  description: ''
  trigger:
  - device_id: 2700d554b05e46d0ad27df6357d67e8d
    domain: light
    entity_id: light.lamp_werkkamer
    platform: device
    type: turned_on
  condition:
  - after: sunset
    condition: sun
  action:
  - data:
      brightness: 100
      entity_id: light.werkkamer
      transition: 5
    service: light.turn_on
- id: '1573073003121'
  alias: badkamer switch
  description: ''
  trigger:
  - entity_id: light.badkamerlamp
    platform: state
    to: 'on'
  condition:
  - after: '21:00:00'
    before: 08:00:00
    condition: time
  action:
  - data:
      brightness: 120
      entity_id: light.badkamerlamp
    service: light.turn_on
- id: '1574879017101'
  alias: Blob aan bij beweging in de nacht
  description: ''
  trigger:
  - device_id: 9a67f97880b7410aa775a8fe0664e47e
    domain: binary_sensor
    entity_id: binary_sensor.presence_15
    platform: device
    type: motion
  condition:
  - after: '19:00:00'
    before: 06:10:00
    condition: time
  - condition: state
    entity_id: light.eettafel
    state: 'off'
  - condition: state
    entity_id: light.blob
    state: 'off'
  action:
  - alias: ''
    data:
      brightness: 44
      color_temp: 432
      entity_id: light.blob
    service: light.turn_on
  - delay: 00:04:00
  - data:
      entity_id: light.blob
    service: light.turn_off
