- id: '1570216531721'
  alias: Stroom van computer onder 5.7 Watt
  trigger:
  - platform: time
    at: '22:00:00'
  condition:
  - condition: numeric_state
    entity_id: sensor.switch_desk_power
    above: '0.5'
    below: '5.7'
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.switch_desk
    data: {}
  mode: restart
- id: '1570300078319'
  alias: Slaapkamer lamp uit om 9 uur
  trigger:
  - at: 09:00:00
    platform: time
  condition: []
  action:
  - data: {}
    service: light.turn_off
    target:
      entity_id: light.slaapkamer
- id: tasmota_auto_discovery
  alias: Sync Tasmota states on start-up - autodiscovery
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: tasmotas/cmnd/state
      payload: ''
- id: '1589008788991'
  alias: Notify everyone when washingmachine is ready
  description: ''
  trigger:
  - entity_id: sensor.washer_samsung_washer_machine_state
    from: run
    platform: state
    to: stop
  condition: []
  action:
  - service: notify.notify
    data_template:
      message: De wasmachine is klaar sinds {{ now().strftime('%H:%M') }}
      title: Wasmachine klaar.
- id: '1600802848971'
  alias: Slaapkamerlamp rood in de avond
  description: Licht op rood als de zon onder is. (handmatig via interface)
  trigger:
  - platform: state
    entity_id:
    - light.color_temperature_light_12
    from: 'off'
    to: 'on'
  condition:
  - condition: sun
    after: sunset
  action:
  - service: light.turn_on
    data:
      brightness: 130
      rgb_color:
      - 255
      - 129
      - 1
    target:
      entity_id: light.slaapkamer
  mode: single
- id: '1613596440486'
  alias: activeer adguard iedere avond
  description: ''
  trigger:
  - platform: time
    at: 00:00
  condition: []
  action:
  - type: turn_on
    device_id: 6a8aa4b9a28e4dc7b4974b55c0b48f4a
    entity_id: switch.adguard_protection
    domain: switch
  mode: single
- id: '1631534925222'
  alias: deurbel
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.doorbell
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.notify
    data:
      title: "\U0001F514 Ding Dong"
      message: 'Er is aangebeld om {{ as_timestamp(states.binary_sensor.doorbell.last_changed)|
        timestamp_custom(''%H:%M'') }} '
      data:
        visibility: public
        channel: Gemiddeld
        importance: high
  - service: notify.google_cloud_message
    data:
      title: "\U0001F514 Ding Dong"
      data:
        ttl: 86400
        priority: high
      message: 'Er is aangebeld om {{ as_timestamp(states.binary_sensor.doorbell.last_changed)|
        timestamp_custom(''%H:%M'') }} '
  mode: single
- id: '1640700155093'
  alias: Tuinlampen aan bij beweging na zonsondergang
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.presence_5
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: state
    entity_id: light.tuin_rechts_1
    state: 'off'
  action:
  - service: light.turn_on
    data:
      transition: 4
    target:
      entity_id: light.tuin
  - delay:
      hours: 0
      minutes: 3
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.tuin
  mode: single
- id: '1641888041487'
  alias: Tuin - lampen uit om 11 uur
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition:
  - condition: state
    entity_id: binary_sensor.presence_5
    state: 'off'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  action:
  - type: turn_off
    device_id: 625bc18c04b0511ba7b52f8e9c98f928
    entity_id: light.tuin
    domain: light
  - type: turn_off
    device_id: dbba5673c4da80c442f44ff6dd98177e
    entity_id: switch.fairy_lights
    domain: switch
  mode: single
- id: smoke_detected
  alias: Brandalarm
  description: ''
  trigger:
  - type: smoke
    platform: device
    device_id: 904bfdae499048b49c88313e1eef19bc
    entity_id: binary_sensor.lumi_sensor_smoke
    domain: binary_sensor
  - type: smoke
    platform: device
    device_id: 904bfdae499048b49c88313e1eef19bc
    entity_id: binary_sensor.lumi_sensor_smoke
    domain: binary_sensor
  condition: []
  action:
  - service: media_player.join
    data:
      group_members:
      - media_player.sonos_slaapkamer
      - media_player.sonos_woonkamer
  - data:
      volume_level: '.80'
    service: media_player.volume_set
    target:
      entity_id:
      - media_player.sonos_slaapkamer
      - media_player.sonos_woonkamer
  - data_template:
      entity_id: media_player.sonos_slaapkamer
      language: nl
      message: Let op, er is rook gedetecteerd {% if is_state('binary_sensor.lumi_sensor_smoke_2',
        'on') %}op de bovenverdieping{% else %}beneden{% endif %}!
    service: tts.google_translate_say
  - service: persistent_notification.create
    data_template:
      message: Er is rook gedetecteerd {% if is_state('binary_sensor.lumi_sensor_smoke_2',
        'on') %}boven{% else %}beneden{% endif %}!
      title: Let op, rook gedeteceerd
  - data_template:
      entity_id: media_player.sonos_slaapkamer
      language: nl
      message: Let op, er is rook gedetecteerd {% if is_state('binary_sensor.lumi_sensor_smoke_2',
        'on') %}op de bovenverdieping{% else %}beneden{% endif %}!
    service: tts.google_translate_say
  - service: notify.mobile_phones
    data:
      data:
        ttl: 0
        priority: high
        channel: Alarm
        importance: high
        timeout: 20000000
        message: Let op, er is rook gedetecteerd {% if is_state('binary_sensor.lumi_sensor_smoke_2',
          'on') %}op de bovenverdieping{% else %}beneden{% endif %}!
- id: '1668094493519'
  alias: Shutters openen om 8:30
  description: ''
  trigger:
  - platform: time
    at: 08:30:00
  condition: []
  action:
  - service: cover.open_cover
    data: {}
    target:
      entity_id:
      - cover.shutter_extra_kamer
      - cover.shutter_inloopkast
  mode: single
