homeassistant:
    # Name of the location where Home Assistant is running
    name: Kerkhuus
    # Location required to calculate the time the sun rises and sets
    latitude: !secret latitude
    longitude: !secret longitude
    # Impacts weather/sunrise data (altitude above sea level in meters)
    elevation: !secret elevation
    unit_system: metric
    external_url: !secret external_url
    internal_url: !secret internal_url
    time_zone: Europe/Amsterdam
    country: NL
    packages: !include_dir_named packages
    customize: !include customize.yaml
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
    ip_ban_enabled: true
    login_attempts_threshold: 10
    ssl_certificate: /ssl/fullchain.pem
    ssl_key: /ssl/privkey.pem

#themes
frontend:
  themes: !include_dir_merge_named themes

mqtt_statestream:
  base_topic: homeassistant
  publish_attributes: true
  publish_timestamps: true
  
# Text to speech
tts:
  - platform: google_translate
 
google_assistant:
  project_id: smart-home-173dd
#  service_account: !include SERVICE_ACCOUNT.JSON
#  report_state: true
#  exposed_domains:
#    - switch
#    - light
#    - cover
#    - group
system_health:
cloud:
notify: !include notifiers.yaml
sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include switches.yaml
scene: !include scenes.yaml