homeassistant:
    # Name of the location where Home Assistant is running
    name: Kerkhuus
    # Location required to calculate the time the sun rises and sets
    latitude: !secret latitude
    longitude: !secret longitude
    # Impacts weather/sunrise data (altitude above sea level in meters)
    elevation: !secret elevation
    unit_system: metric
    time_zone: Europe/Amsterdam
    packages: !include_dir_named packages
    customize: !include customize.yaml
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
    base_url: !secret duckdns
    ip_ban_enabled: true
    login_attempts_threshold: 5
    ssl_certificate: /ssl/fullchain.pem
    ssl_key: /ssl/privkey.pem

# Discover some devices automatically
discovery:
#themes
frontend:
  themes: !include themes.yaml
  
# Text to speech
tts:
  - platform: google_translate
    base_url: !secret tts_url
  
#weer 
weather:
  - platform: buienradar

#google calendar
google:
  client_id: !secret google_calendar_id
  client_secret: !secret google_calendar_secret

wake_on_lan:
  PC: "30:5a:3a:45:ed:7a"
  name: "PC"
  host: 192.168.2.19
  turn_on:
    service: hassio.addon_stdin
    data:
      addon: core_rpc_shutdown
      input: PC
  turn_off:
    service: hassio.addon_stdin
    data:
      addon: core_rpc_shutdown
      input: PC

camera:
  - platform: ffmpeg
    name: DaFang3_1
    input: -rtsp_transport tcp -i rtsp://192.168.3.11:8554/unicast
    
sonos:
  media_player:
    hosts:
      - 192.168.10.8
      
updater:
system_health:
notify: !include notifiers.yaml
sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include switches.yaml
scene: !include scenes.yaml