- platform: time_date
  display_options:
      - 'time'
      - 'date'
- platform: nederlandse_spoorwegen
  api_key: !secret ns_password
  routes:
    - name: Gouda - Rotterdam
      from: Gd
      to: Rtd
- platform: systemmonitor
  resources:
  - type: processor_use
  - type: memory_free
  - type: disk_use
    arg: /home
  - type: network_in
    arg: eno1
  - type: network_out
    arg: eno1
  - type: disk_free
    arg: /home
  - type: last_boot
- platform: afvalbeheer
  wastecollector: Cyclus
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: !secret postcode
  streetnumber: !secret straat_nr
  upcomingsensor: 1
  nameprefix: 1
  builtinicons: 1
  dutch: 1
- platform: min_max
  name: Gemiddelde temperatuur
  type: mean
  entity_ids:
    - sensor.multi_sensor_2_3
    - sensor.multi_sensor