- platform: time_date
  display_options:
      - 'time'
      - 'date'
- platform: nederlandse_spoorwegen
  email: !secret ns_username
  password: !secret ns_password
  routes:
    - name: Gouda - Rotterdam
      from: Gd
      to: Rtd
    - name: Gouda - Woerden
      from: Gd
      to: Wd
- platform: systemmonitor
  resources:
  - type: processor_use
  - type: memory_free
  - type: disk_free
    arg: /home
  - type: last_boot
  
- platform: google_travel_time
  scan_interval: 10
  api_key: !secret google_maps_api_key
  origin: place_id:ChIJ9Q9i66vWxUcRdT0RSzIkMZw
  destination: place_id:ChIJ06BR_qQ0xEcRd8UVFPb3HEs
  options:
    mode: transit
    transit_mode: train
    language: nl