- platform: time_date
  display_options:
      - 'time'
      - 'date'
- platform: afvalbeheer
  wastecollector: Cyclus
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: !secret postcode
  streetnumber: !secret straat_nr
  upcomingsensor: 1
  nameprefix: 1
  builtinicons: 1
  dutch: 1
- platform: min_max
  name: Gemiddelde temperatuur
  type: mean
  entity_ids:
    - sensor.multi_sensor_2_3
    - sensor.multi_sensor