input_datetime:
  alarm_tue:
    name: Alarm tijd
    has_date: false
    has_time: true
    
input_number:
  alarm_tue_offset:
    name: Transitie tijd
    icon: mdi:blur-linear
    initial: 10
    min: 0
    max: 60
    step: 5
    
input_boolean:
  alarm_tue_enable:
    name: "Alarm aanzetten"


sensor:
  - platform: template
    sensors:
      alarm_tue_time:
        friendly_name: 'Muziek gaat spelen om'
        value_template: "{{ ((states.input_datetime.alarm_tue.attributes.timestamp) | timestamp_custom('%H:%M', False)) }}"
  - platform: template
    sensors:
      alarm_tue_time_minus_offset:
        friendly_name: 'Lamp gaat aan om'
        value_template: "{{ (states.input_datetime.alarm_tue.attributes.timestamp - ((states('input_number.alarm_tue_offset' ) | int) * 60)) | timestamp_custom('%H:%M', False) }}"
group:
  alarm_tue:
    name: Alarm dinsdag
    entities:
    - input_boolean.alarm_tue_enable
    - sensor.alarm_tue_time
    - sensor.alarm_tue_time_minus_offset
    - input_datetime.alarm_tue
    - input_number.alarm_tue_offset
    
    
# The automation for the Alarm clock.
automation:
- id: alarm_tue
  alias: 'Wakker worden op dinsdag.'
  trigger:
    - platform: time_pattern
      minutes: '/1'
      seconds: 00
  condition:
    - condition: template
      value_template: "{{ states.sensor.time.state == states.sensor.alarm_tue_time_minus_offset.state  }}"
    - condition: state
      entity_id: input_boolean.alarm_tue_enable  
      state: 'on'
    - condition: time
      weekday: 
        - tue
  action:
  - service: script.bedroom_wakeup
    data_template:
          alarm_offset: "{{states('input_number.alarm_tue_offset')| int }}"