input_datetime:
  alarm_sun:
    name: Alarm tijd
    has_date: false
    has_time: true
    
input_number:
  alarm_sun_offset:
    name: Transitie tijd
    icon: mdi:blur-linear
    min: 0
    max: 60
    step: 5
    
input_boolean:
  alarm_sun_enable:
    name: "Alarm aanzetten"


sensor:
  - platform: template
    sensors:
      alarm_sun_time:
        friendly_name: 'Muziek gaat spelen om'
        value_template: "{{ ((states.input_datetime.alarm_sun.attributes.timestamp) | timestamp_custom('%H:%M', False)) }}"
  - platform: template
    sensors:
      alarm_sun_time_minus_offset:
        friendly_name: 'Lamp gaat aan om'
        value_template: "{{ (states.input_datetime.alarm_sun.attributes.timestamp - ((states('input_number.alarm_sun_offset' ) | int) * 60)) | timestamp_custom('%H:%M', False) }}"
group:
  alarm_sun:
    name: Alarm zondag
    entities:
    - input_boolean.alarm_sun_enable
    - sensor.alarm_sun_time
    - sensor.alarm_sun_time_minus_offset
    - input_datetime.alarm_sun
    - input_number.alarm_sun_offset
    
    
# The automation for the Alarm clock.
automation:
- id: alarm_sun
  alias: 'Wakker worden op zondag.'
  hide_entity: true
  trigger:
    - platform: time_pattern
      minutes: '/1'
      seconds: 00
  condition:
    - condition: template
      value_template: "{{ states.sensor.time.state == states.sensor.alarm_sun_time_minus_offset.state  }}"
    - condition: state
      entity_id: input_boolean.alarm_sun_enable  
      state: 'on'
    - condition: time
      weekday: 
        - sun
  action:
  - service: script.bedroom_wakeup
    data_template:
          alarm_offset: "{{states('input_number.alarm_sun_offset')| int }}"