input_boolean:
  before_sleep_enable:
    name: "Trusten!"

automation:
- id: before_sleep
  alias: 'Voor het slapen gaan.'
  trigger:
  - entity_id: input_boolean.before_sleep_enable
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: or
    conditions:
    - condition: and
      conditions:
      - condition: time
        weekday: 
        - sun
        - thu
        - thu
      - before: '22:00:00'
        condition: time
    - condition: time
      weekday: 
      - mon
      - wed
      - fri
      - sat
  action:
    service: scene.turn_on
    entity_id:  scene.slaapkamer_voor_het_slapen_gaan