automation:
- id: good_morning_message
  alias: Goedemorgen bericht
  description: ''
  trigger: []
  condition: []
  action:
  - service: tts.google_translate_say
    data_template:
      language: nl
      message: >
        {% if now().strftime("%H")|int < 12 %}
        Goodemorgen,
        {% elif now().strftime("%H")|int < 18 %}
        Goedemiddag,
        {% else %}
        Goedeavond,
        {% endif %}
        De temperatuur in huis is {{ states("sensor.gemiddelde_temperatuur") }} °C en buiten is het momenteel {{ state_attr("weather.huis", "temperature")  }} °C.
        Het wordt vandaag
        {% if states.sensor.br_temperature.state | int < 0 %}
          erg koud met een temperatuur van {{states('sensor.br_temperature')|round}} graden, let op het kan glad zijn.
          {% elif states.sensor.br_temperature.state | int < 10 %}
          koud met een temperatuur van {{states('sensor.br_temperature')|round}} graden.   
          {% elif states.sensor.br_temperature.state | int < 15 %}
          fris met een temperatuur van {{states('sensor.br_temperature')|round}} graden.
          {% elif states.sensor.br_temperature.state | int < 20 %}
          lekker met een temperatuur van {{states('sensor.br_temperature')|round}} graden.
          {% elif states.sensor.br_temperature.state | int > 20 %}
          warm met een temperatuur van {{states('sensor.br_temperature')|round}} graden.          
          {% endif %}
          Het wordt vandaag
          {% if states.sensor.br_temperature_1d.state | int < 0 %}
          erg koud met een maximale temperatuur van {{states('sensor.br_temperature_1d')|round}} graden.
          {% elif states.sensor.br_temperature_1d.state | int < 10 %}
          koud met een maximale temperatuur van {{states('sensor.br_temperature_1d')|round}} graden.   
          {% elif states.sensor.br_temperature_1d.state | int < 15 %}
          fris met een maximale temperatuur van {{states('sensor.br_temperature_1d')|round}} graden.
          {% elif states.sensor.br_temperature_1d.state | int < 20 %}
          lekker met een maximale temperatuur van {{states('sensor.br_temperature_1d')|round}} graden.
          {% elif states.sensor.br_temperature_1d.state | int > 20 %}
          warm met een maximale temperatuur van {{states('sensor.br_temperature_1d')|round}} graden.          
          {% endif %}
          De kans op regen is vandaag
          {% if states.sensor.br_rainchance_1d.state | int < 25 %}
          heel erg klein met een kans van {{states('sensor.br_rainchance_1d')|round}} procent.
          {% elif states.sensor.br_rainchance_1d.state | int < 50 %}
          klein met een kans van {{states('sensor.br_rainchance_1d')|round}} procent.            
          {% elif states.sensor.br_rainchance_1d.state | int < 75 %}
          groot met een kans van {{states('sensor.br_rainchance_1d')|round}} procent.  
          {% elif states.sensor.br_rainchance_1d.state | int > 75 %}
          heel groot met een kans van {{states('sensor.br_rainchance_1d')|round}} procent.
          {% endif %}
          #De windkracht is vandaag
          #{% if states.sensor.br_wind_force_1d.state | int < 2 %}
          #erg laag met een windkracht van {{states('sensor.br_wind_force_1d')|round}}.
          #{% elif states.sensor.br_wind_force_1d.state | int < 4 %}
          #laag met een windkracht van{{states('sensor.br_wind_force_1d')|round}}.            
          #{% elif states.sensor.br_wind_force_1d.state | int < 6 %}
          #hoog met een windkracht van{{states('sensor.br_wind_force_1d')|round}}.  
          #{% elif states.sensor.br_wind_force_1d.state | int > 6 %}
          #erg hoog met een windkracht van {{states('sensor.br_wind_force_1d')|round}} let op windstoten.
          #{% endif %}